baseURL = "https://analyst-huang.github.io/"
languageCode = "zh-cn"
title = "Blog"
theme = "PaperMod"

pagination.pagerSize = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  math = true

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON 用于生成搜索索引

[[menu.main]]
  name = "Search"
  url = "search/"
  weight = 10

